// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Notlar.Models;

namespace Notlar.Migrations
{
    [DbContext(typeof(NotDbContext))]
    [Migration("20220608094517_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Notlar.Models.Notlar", b =>
                {
                    b.Property<int>("NotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("NotBaslik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotIcerik")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NotId");

                    b.ToTable("Notlar");
                });
#pragma warning restore 612, 618
        }
    }
}
